import { StyleSheet } from 'react-native';

export const colors = {
  ink: '#16212B',
  green: '#31594C',
  deep: '#1B2E2B',
  paper: '#F7F6F2',
  mint: '#E8F0E7',
  lime: '#DDF56A',
  muted: '#78827F',
  line: '#E6E8E2',
  placeholder: '#87909D',
};

export const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.paper },
  loading: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.paper },
  header: { paddingHorizontal: 24, paddingTop: 12, paddingBottom: 14, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  wordmark: { fontSize: 27, fontWeight: '800', letterSpacing: -1.1, color: colors.ink },
  subhead: { fontSize: 12, color: '#66707B', marginTop: 1 },
  plusPill: { backgroundColor: colors.lime, borderRadius: 18, paddingHorizontal: 12, paddingVertical: 7 },
  plusText: { fontSize: 11, fontWeight: '800', letterSpacing: 1, color: colors.ink },
  content: { paddingHorizontal: 20, paddingBottom: 100 },

  hero: { borderRadius: 28, backgroundColor: colors.deep, padding: 25, marginBottom: 16 },
  eyebrow: { color: '#9DE7D0', fontSize: 11, fontWeight: '800', letterSpacing: 1.5, marginBottom: 12 },
  eyebrowDark: { color: '#688A7F', fontSize: 11, fontWeight: '800', letterSpacing: 1.5, marginBottom: 10 },
  heroTitle: { color: '#F4F3E9', fontWeight: '800', fontSize: 34, letterSpacing: -1.5, lineHeight: 38 },
  heroCopy: { color: '#C3D4CE', fontSize: 15, lineHeight: 22, marginTop: 12, maxWidth: 260 },
  statRow: { flexDirection: 'row', gap: 28, marginTop: 24 },
  statValue: { color: '#F4F3E9', fontWeight: '800', fontSize: 26 },
  statLabel: { color: '#AFC5BE', fontSize: 12, marginTop: 2 },
  sectionTitle: { color: colors.ink, fontWeight: '800', fontSize: 20, marginBottom: 13, marginTop: 10 },

  howCard: { backgroundColor: '#FFF', borderRadius: 22, padding: 20, marginBottom: 16, borderWidth: 1, borderColor: colors.line },
  howStep: { flexDirection: 'row', alignItems: 'center', marginTop: 10 },
  howNumber: { width: 28, height: 28, borderRadius: 14, backgroundColor: colors.lime, alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  howNumberText: { fontWeight: '800', color: colors.ink, fontSize: 13 },
  howStepText: { flex: 1, color: colors.ink, fontSize: 15, fontWeight: '700' },

  nextCard: { backgroundColor: colors.mint, borderRadius: 22, padding: 20, marginBottom: 16 },
  nextTitle: { color: colors.ink, fontSize: 19, fontWeight: '800', lineHeight: 24 },
  nextReason: { color: '#52665F', fontSize: 13, lineHeight: 18, marginTop: 6 },

  planCard: { backgroundColor: '#FFF', borderRadius: 18, padding: 16, marginBottom: 10, borderWidth: 1, borderColor: colors.line },
  planText: { color: colors.ink, fontWeight: '700', fontSize: 14 },
  planBar: { flexDirection: 'row', gap: 6, marginTop: 10 },
  planSegment: { flex: 1, height: 8, borderRadius: 4, backgroundColor: colors.mint },
  planSegmentFilled: { backgroundColor: colors.green },
  planHint: { color: colors.muted, fontSize: 12, marginTop: 8 },

  mission: { backgroundColor: '#FFF', borderRadius: 18, padding: 16, marginBottom: 10, flexDirection: 'row', alignItems: 'center' },
  number: { width: 37, height: 37, borderRadius: 12, backgroundColor: colors.mint, justifyContent: 'center', alignItems: 'center', marginRight: 13 },
  numberText: { color: colors.green, fontWeight: '800' },
  missionCopy: { flex: 1 },
  missionMeta: { fontSize: 11, color: '#71807C', fontWeight: '700', marginBottom: 4 },
  missionTitle: { color: colors.ink, fontSize: 16, fontWeight: '700', lineHeight: 21 },
  missionOutcome: { color: colors.green, fontSize: 12, marginTop: 4 },
  arrow: { color: colors.green, fontSize: 23 },

  nav: { backgroundColor: '#FFF', height: 68, flexDirection: 'row', borderTopWidth: 1, borderTopColor: '#E8E9E5', paddingHorizontal: 25 },
  navItem: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  navText: { fontSize: 13, fontWeight: '700', color: '#8A918E' },
  navTextActive: { color: colors.green },

  modal: { flex: 1, backgroundColor: colors.paper },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', padding: 22, alignItems: 'center' },
  modalBrand: { fontWeight: '800', fontSize: 18, color: colors.ink },
  close: { color: colors.green, fontWeight: '700', fontSize: 15 },
  modalContent: { padding: 24, paddingTop: 8, paddingBottom: 48 },
  modalTitle: { color: colors.ink, fontWeight: '800', fontSize: 29, letterSpacing: -1, lineHeight: 34, marginBottom: 12 },
  body: { color: '#59646D', fontSize: 15, lineHeight: 22 },
  inputLabel: { color: colors.ink, fontWeight: '800', fontSize: 14, marginTop: 28, marginBottom: 8 },
  required: { color: '#B34B37' },
  input: { minHeight: 112, backgroundColor: '#FFF', borderWidth: 1, borderColor: '#E2E4DE', borderRadius: 16, padding: 14, textAlignVertical: 'top', fontSize: 15, color: colors.ink, lineHeight: 21 },
  primaryButton: { backgroundColor: colors.green, borderRadius: 16, alignItems: 'center', justifyContent: 'center', paddingVertical: 16, marginTop: 28 },
  primaryButtonText: { color: '#FFF', fontSize: 15, fontWeight: '800' },
  secondaryButton: { borderRadius: 16, alignItems: 'center', justifyContent: 'center', paddingVertical: 15, marginTop: 12, borderWidth: 1.5, borderColor: colors.green },
  secondaryButtonText: { color: colors.green, fontSize: 15, fontWeight: '800' },
  compactButton: { marginTop: 14, paddingVertical: 12 },
  helper: { color: colors.muted, fontSize: 12, textAlign: 'center', lineHeight: 17, marginTop: 12 },

  checklist: { backgroundColor: '#FFF', borderRadius: 16, padding: 16, marginTop: 24, borderWidth: 1, borderColor: colors.line },
  checklistTitle: { color: colors.ink, fontWeight: '800', fontSize: 14, marginBottom: 4 },
  checklistNote: { color: colors.muted, fontSize: 12, lineHeight: 17, marginBottom: 6 },
  checkRow: { flexDirection: 'row', alignItems: 'flex-start', marginTop: 10 },
  checkIcon: { width: 22, height: 22, borderRadius: 11, borderWidth: 1.5, borderColor: '#C9CEC6', alignItems: 'center', justifyContent: 'center', marginRight: 10, marginTop: 1 },
  checkIconMet: { backgroundColor: colors.green, borderColor: colors.green },
  checkMark: { color: '#FFF', fontSize: 12, fontWeight: '800' },
  checkCopy: { flex: 1 },
  checkLabel: { color: colors.ink, fontSize: 14, fontWeight: '700' },
  checkRule: { color: colors.muted, fontSize: 12, lineHeight: 16, marginTop: 2 },

  empty: { marginTop: 24, backgroundColor: '#FFF', padding: 28, borderRadius: 22, alignItems: 'center' },
  emptyTitle: { fontSize: 24, lineHeight: 29, color: colors.ink, fontWeight: '800', marginBottom: 10, textAlign: 'center' },
  emptyBody: { color: '#59646D', fontSize: 15, lineHeight: 22, textAlign: 'center' },
  trailArt: { alignItems: 'center', marginBottom: 22 },
  trailDot: { width: 18, height: 18, borderRadius: 9, backgroundColor: colors.mint, borderWidth: 2, borderColor: '#C9D9CF' },
  trailLine: { width: 2, height: 18, backgroundColor: '#C9D9CF' },
  trailStart: { width: 56, height: 56, borderRadius: 28, backgroundColor: colors.lime, alignItems: 'center', justifyContent: 'center' },
  trailEmoji: { fontSize: 26 },

  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 16 },
  chip: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 18, backgroundColor: '#FFF', borderWidth: 1, borderColor: colors.line },
  chipActive: { backgroundColor: colors.green, borderColor: colors.green },
  chipText: { color: colors.green, fontWeight: '700', fontSize: 13 },
  chipTextActive: { color: '#FFF' },

  card: { backgroundColor: '#FFF', padding: 20, borderRadius: 24, marginBottom: 15, borderWidth: 1, borderColor: colors.line },
  cardMeta: { color: '#688A7F', fontWeight: '800', fontSize: 10, letterSpacing: 1, marginBottom: 9 },
  cardTitle: { color: colors.ink, fontSize: 22, lineHeight: 26, fontWeight: '800', marginBottom: 18 },
  cardLabel: { color: colors.muted, fontWeight: '800', fontSize: 10, letterSpacing: 1.1, marginTop: 12, marginBottom: 5 },
  cardText: { color: '#3D4951', fontSize: 14, lineHeight: 20 },
  cardFooter: { borderTopColor: '#E9EBE5', borderTopWidth: 1, marginTop: 19, paddingTop: 13, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  cardBrand: { color: colors.green, fontWeight: '800', fontSize: 13 },
  verified: { color: colors.green, fontWeight: '700', fontSize: 11 },
  shareButton: { marginTop: 14, borderRadius: 14, paddingVertical: 11, alignItems: 'center', backgroundColor: colors.mint },
  shareButtonText: { color: colors.green, fontWeight: '800', fontSize: 14 },

  overlay: { flex: 1, backgroundColor: 'rgba(13,25,22,.5)', alignItems: 'center', justifyContent: 'center', padding: 20 },
  paywall: { width: '100%', maxWidth: 480, backgroundColor: '#FCFBF7', borderRadius: 28, padding: 26 },
  dismiss: { alignSelf: 'flex-end', marginTop: -8 },
  paywallTitle: { fontSize: 29, letterSpacing: -1, lineHeight: 34, color: colors.ink, fontWeight: '800', marginBottom: 20 },
  benefit: { color: '#35453F', fontSize: 15, marginVertical: 7, fontWeight: '600' },
  paywallStatus: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10, marginTop: 20 },
  paywallStatusText: { color: colors.muted, fontSize: 13 },
  buttonDisabled: { opacity: 0.45 },
  notice: { borderRadius: 14, padding: 14, marginTop: 16 },
  noticeInfo: { backgroundColor: colors.mint },
  noticeSuccess: { backgroundColor: '#E4F5C4' },
  noticeError: { backgroundColor: '#F8E1DB' },
  noticeText: { color: colors.ink, fontSize: 13, lineHeight: 18 },
  noticeAction: { color: colors.green, fontWeight: '800', fontSize: 13, marginTop: 8 },

  profileCircle: { width: 64, height: 64, borderRadius: 32, backgroundColor: colors.lime, justifyContent: 'center', alignItems: 'center', marginTop: 10, marginBottom: 20 },
  profileInitial: { fontSize: 26, fontWeight: '800', color: colors.ink },
  profileTitle: { fontSize: 28, letterSpacing: -1, lineHeight: 33, color: colors.ink, fontWeight: '800', marginBottom: 10 },
  profileStats: { flexDirection: 'row', gap: 32, backgroundColor: colors.deep, padding: 20, borderRadius: 18, marginTop: 25 },
  status: { marginTop: 18, padding: 18, borderRadius: 17, backgroundColor: colors.mint },
  statusTitle: { fontWeight: '800', color: colors.green, marginBottom: 5 },
  statusText: { color: '#52665F', fontSize: 13, lineHeight: 18 },

  onboard: { flex: 1, backgroundColor: colors.paper, padding: 24 },
  skip: { alignSelf: 'flex-end', paddingVertical: 8, paddingHorizontal: 4 },
  onboardBody: { flex: 1, justifyContent: 'center' },
  onboardVisual: { width: 96, height: 96, borderRadius: 32, backgroundColor: colors.deep, alignItems: 'center', justifyContent: 'center', marginBottom: 32 },
  onboardEmoji: { fontSize: 44 },
  onboardTitle: { fontSize: 36, lineHeight: 40, letterSpacing: -1.5, fontWeight: '800', color: colors.ink, marginBottom: 16 },
  dots: { flexDirection: 'row', gap: 8, marginBottom: 8 },
  dot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#C9CEC6' },
  dotActive: { width: 24, backgroundColor: colors.green },
});
